# Generated by Django 4.1.1 on 2022-09-09 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Direcciones', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(blank=True, max_length=100)),
                ('telefono', models.CharField(max_length=100)),
                ('domicilio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_domicio', to='Direcciones.domicilio')),
                ('instalador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_empleado', to='Usuarios.empleado')),
            ],
        ),
    ]
