# Generated by Django 4.1.1 on 2022-09-08 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Empleados', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(blank=True, max_length=100)),
                ('telefono', models.CharField(max_length=100)),
                ('instalador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empleado_usuario', to='Empleados.empleado')),
            ],
        ),
    ]
