# Generated by Django 4.1.1 on 2022-09-09 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Equipo', '0001_initial'),
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='equipo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_equipo', to='Equipo.equipo'),
            preserve_default=False,
        ),
    ]
